config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  root to: 'homes#top'
  resources :customers, only: [:show, :edit, :update]
  resources :animals
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :calculation, only: [:index, :show]

  get '/search', to: 'searches#search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :customers, expect: [:new, :destroy, :create]
    resources :animals, expect: [:new, :create, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animal.rb
class Animal < ApplicationRecord
  # has_many_attached :images
  attachment :image

  belongs_to :customer
  has_many :searches

  enum tipe: { dog: 0, cat: 1}
  enum sex: { bothsides: 0, male: 1, female: 2}
  enum vaccine: { unknown: 0, already: 1, notyet: 2}
  enum castrate: { humei: 0, sumi: 1, mada: 2}

  scope :search, -> (search_params) do
    return if search_params.blank?

    profile_like(search_params[:profile])
      .prefecture_like(search_params[:gender])
      .tipe_is(search_params[:sex])
      .sex_is(search_params[:gender])
      .vaccine_is(search_params[:gender])
      .castrate_is(search_params[:gender])
  end

  scope :profile_like, -> (profile) { where('profile LIKE ?', "%#{profile}%") if profile.present? }
  scope :prefecture_like, -> (prefecture) { where('prefecture LIKE ?', "%#{prefecture}%") if prefecture.present? }
  scope :tipe_is, -> (tipe) { where(tipe: tipe) if tipe.present? }
  scope :sex_is, -> (sex) { where(sex: sex) if sex.present? }
  scope :vaccine_is, -> (vaccine) { where(vaccine: vaccine) if vaccine.present? }
  scope :castrate_is, -> (castrate) { where(castrate: castrate) if castrate.present? }

# プロフィールによる絞り込み
# scope :get_by_profile, ->profile {
# where("profile like ?", "%#{profile}%")
# }
# 種類による絞り込み
# scope :get_by_tipe, ->(tipe) {
# where(tipe: tipe)
# }

# 性別による絞り込み
# scope :get_by_sex, ->(sex) {
# where(sex: sex)
# }

# ワクチンによる絞り込み
# scope :get_by_vaccine, ->(vaccine) {
# where(vaccine: vaccine)
# }

# 去勢手術による絞り込み
# scope :get_by_castrate, ->(castrate) {
# where(castrate: castrate)
# }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord

  def tribonacci(n)
  return   if n < 1
  a, b, c = 0, 0, 1
  (n - 1).times { a, b, c = b, c, a + b + c }
  a
  end

  def tribonacci n
  if n == 1
    return 1
  elsif n == 2
    return 1
  elsif n == 3
    return 2
  else
    return tribonacci(n - 3) + tribonacci(n - 2) + tribonacci(n - 1)
  end
　end

　def yakusuu

　end

　def fibonacci(input)
  (2...input).inject([1, 1]){ |memo, number|
    memo << (memo[number - 2] + memo[number - 1])
  }
  end

  p fibonacci(10)
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/divisor.rb
class Divisor < ApplicationRecord
  def divisor(num)
  result = []
  i = 1
  while i <= num do
    remainder = num % i
    if remainder == 0
      result << i
    end 
    i += 1
  end
  return result
end

puts "約数を算出したい整数を入力してください"
num = gets.to_i
r = divisor(num)
puts r
puts "約数の数は#{r.length}です"
puts "約数の合計は#{r.sum}です"

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :customer
  belongs_to :room
end

app/models/mini.rb
class Mini < ApplicationRecord
end

app/models/minipro.rb
class Minipro < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :customer
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :animal

  scope :search, -> (search_params) do
    return if search_params.blank?

    profile_like(search_params[:profile])
      .prefecture_like(search_params[:prefecture])
      .tipe_is(search_params[:tipe])
      .sex_is(search_params[:sex])
      .vaccine_is(search_params[:vaccine])
      .castrate_is(search_params[:castrate])
  end

  scope :profile_like, -> (profile) { where('profile LIKE ?', "%#{profile}%") if profile.present? }
  scope :prefecture_like, -> (prefecture) { where('prefecture LIKE ?', "%#{prefecture}%") if prefecture.present? }
  scope :tipe_is, -> (tipe) { where(tipe: tipe) if tipe.present? }
  scope :sex_is, -> (sex) { where(sex: sex) if sex.present? }
  scope :vaccine_is, -> (vaccine) { where(vaccine: vaccine) if vaccine.present? }
  scope :castrate_is, -> (castrate) { where(castrate: castrate) if castrate.present? }


end

app/controllers/admin/animals_controller.rb
class Admin::AnimalsController < ApplicationController
  def index
    @animals = Animal.page(params[:page])
  end

  def show
    @animal = Animal.find(params[:id])
  end

  # 自動処理機能実装後削除予定
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    
  end
  
  private
  
  def animal_params
    params.require(:animal).permit(:image, :title, :tipe, :sex, :birthday, :prefecture, :vaccine, :vaccine_date, :castrate, :profile, :other)
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
before_action :authenticate_customer!, only: [:edit, :new, :show]

before_action :correct_post,only: [:edit]

before_action :set_amimal, only: [:correct_post, :edit, :update, :show, :destroy]


def authenticate_customer!
       unless customer_signed_in?
        redirect_to new_customer_session_path
       end
end

def correct_post
        # @animal = Animal.find(params[:id])
    unless @animal.customer.id == current_customer.id
      redirect_to animals_path
    end
end



  def new
    @animal = Animal.new
  end

  def index
     @search_params = Search.new
     @animals = Animal.all.page(params[:page]).per(8).reverse_order
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.customer_id = current_customer.id
    # @animal = Animal.create params.require(:animal).permit(:title,  :tipe, :sex, :birthday, :prefecture, :vaccine, :vaccine_date, :castrate, :profile, :other, images: [], )
    @animal.save
    redirect_to animal_path(@animal)
  end

  def edit
    # @animal = Animal.find(params[:id])
  end

  def update
    # @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animal_path(@animal.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def show
    # @animal = Animal.find(params[:id])
  end

  def destroy
    # @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to customer_path(current_customer.id)
  end

  private

  
  def set_amimal
    @animal = Animal.find(params[:id])
  end
  
  def animal_params
    params.require(:animal).permit(:image, :title, :tipe, :sex, :birthday, :prefecture, :vaccine, :vaccine_date, :castrate, :profile, :other)
  end

end

app/helpers/admin/animals_helper.rb
module Admin::AnimalsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/java_helper.rb
module JavaHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mini_helper.rb
module MiniHelper
end

app/helpers/minipro_helper.rb
module MiniproHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/animals/index.html.erb
<div class="row">
    <div class="width">
　    <% @animals.each do |animal| %>
　      <div class="height">
          <p class="img_wrap">
            <%= link_to animal_path(animal) do %>
              <%= attachment_image_tag animal, :image, :fill, 250, 250, format: 'jpeg', class: "img" %>
            <% end %>
          </p>
          <p>
            <%= animal.title %>
          </p>
          <p>
            <%= animal.prefecture %>
          </p>
        </div>
　    <% end %>
　    <div class="center-block row">
        <%= paginate @animals %>
      </div>
    </div>
  </div>
</div>

app/views/admin/animals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
    <%= attachment_image_tag @animal, :image, :fill, 300, 300 %>
    <h3><%= @animal.title %></h3>
    </div>
    <div class="col-lg-4 offset-lg-4">
      <table class="table">
        <tr>
          <th>ユーザー名</th>
          <td><%= @animal.customer.user_name %></td>
        </tr>
        <tr>
          <th>所在地</th>
          <td><%= @animal.customer.prefecture %></td>
        </tr>
      </table>
      <% if @animal.customer == current_customer %>
        <%=link_to "編集する", edit_animal_path(@animal), class: "btn btn-sm btn-success" %>
        <%=link_to "削除する", animal_path(@animal),method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
      <% else %>
        <%=link_to "応募画面に行く", customer_path(@animal.customer),  class:"btn btn-primary btn-lg user-show-chat" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th class="customer_edit_th">種類</th>
        <td><%= @animal.tipe_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">性別</th>
        <td><%= @animal.sex_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">誕生日</th>
        <td><%= @animal.birthday %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">所在地</th>
        <td><%= @animal.prefecture %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">ワクチン</th>
        <td><%= @animal.vaccine_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">去勢手術</th>
        <td><%= @animal.castrate_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">プロフィール</th>
        <td><%= @animal.profile %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">その他</th>
        <td><%= @animal.other %></td>
      </tr>
</table>
</div>
</div>

app/views/animals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 i-show-empty">
      <h4 class="pr-3 pt-3">犬猫登録</h4>
      <%= form_with model: @animal, local:true do |f| %>
      <table class="customer_table">
          <tr>
            <th class="customer_edit_th">写真</th>
            <td><%= f.attachment_field :image %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">タイトル</th>
            <td><%= f.text_field :title %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">種類</th>
            <td><%= f.radio_button :tipe, :dog %>犬

            <%= f.radio_button :tipe, :cat %>猫</td>
          </tr>
           <tr>
            <th class="customer_edit_th">性別</th>
            <td><%= f.radio_button :sex, :male %>オス

            <%= f.radio_button :sex, :female %>メス

            <%= f.radio_button :sex, :bothsides %>両方</td>
          </tr>
          <tr>
            <th class="customer_edit_th">お誕生日</th>
            <td><%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1) %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">所在地(都道府県)</th>
            <td><%= f.text_field :prefecture %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">ワクチン</th>
            <td><%= f.radio_button :vaccine, :already %>済

            <%= f.radio_button :vaccine, :notyet %>未

            <%= f.radio_button :vaccine, :unknown %>不明</td>
          </tr>
          <tr>
          　<th class="customer_edit_th">ワクチン接種日</th>
            <td><%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1999, 1, 1) %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">去勢手術</th>
            <td><%= f.radio_button :castrate, :sumi %>済

            <%= f.radio_button :castrate, :mada %>未

            <%= f.radio_button :castrate, :humei %>不明</td>
          </tr>
          <tr>
            <th class="customer_edit_th">プロフィール</th>
            <td><%= f.text_area :profile %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">その他</th>
            <td><%= f.text_area :other %></td>
          </tr>
        </table>
        <div></div>
        <%= f.submit "編集する", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-lg-4">WaNyan</h2>
    <%= link_to "募集する", new_animal_path, class: "col-lg-2 offset-lg-6 btn btn-primary" %>
  </div>
  <div class="row">
    <%= render partial: 'searches/form' %>
  </div>
  <div class="row">
    <div class="width">
　    <% @animals.each do |animal| %>
　      <div class="height">
          <p class="img_wrap">
            <%= link_to animal_path(animal) do %>
              <%= attachment_image_tag animal, :image, :fill, 250, 250, format: 'jpeg', class: "img" %>
            <% end %>
          </p>
          <p>
            <%= animal.title %>
          </p>
          <p>
            <%= animal.prefecture %>
          </p>
        </div>
　    <% end %>
　    <div class="center-block row">
        <%= paginate @animals %>
      </div>
    </div>
  </div>
</div>

app/views/animals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 i-show-empty">
      <h4 class="pr-3 pt-3">募集登録</h4>
      <%= form_with model: @animal, local:true do |f| %>
      <table class="customer_table">
          <tr>
            <th class="customer_edit_th">写真</th>
            <td><%= f.attachment_field :image %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">タイトル</th>
            <td><%= f.text_field :title %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">種類</th>
            <td><%= f.radio_button :tipe, :dog %>犬

            <%= f.radio_button :tipe, :cat %>猫</td>
          </tr>
           <tr>
            <th class="customer_edit_th">性別</th>
            <td><%= f.radio_button :sex, :male %>オス

            <%= f.radio_button :sex, :female %>メス

            <%= f.radio_button :sex, :bothsides %>両方</td>
          </tr>
          <tr>
            <th class="customer_edit_th">お誕生日</th>
            <td><%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, default: Date.new(1989, 1, 1) %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">所在地(都道府県)</th>
            <td><%= f.text_field :prefecture %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">ワクチン</th>
            <td><%= f.radio_button :vaccine, :already %>済

            <%= f.radio_button :vaccine, :notyet %>未

            <%= f.radio_button :vaccine, :unknown %>不明</td>
          </tr>
          <tr>
          　<th class="customer_edit_th">ワクチン接種日</th>
            <td><%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, default: Date.new(1999, 1, 1) %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">去勢手術</th>
            <td><%= f.radio_button :castrate, :sumi %>済

            <%= f.radio_button :castrate, :mada %>未

            <%= f.radio_button :castrate, :humei %>不明</td>
          </tr>
          <tr>
            <th class="customer_edit_th">プロフィール</th>
            <td><%= f.text_area :profile %></td>
          </tr>
          <tr>
            <th class="customer_edit_th">その他</th>
            <td><%= f.text_area :other %></td>
          </tr>
        </table>
        <div></div>
        <%= f.submit "募集する", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
    <%= attachment_image_tag @animal, :image, :fill, 300, 300 %>
    <h3><%= @animal.title %></h3>
    </div>
    <div class="col-lg-4 offset-lg-4">
      <table class="table">
        <tr>
          <th>ユーザー名</th>
          <td><%= @animal.customer.user_name %></td>
        </tr>
        <tr>
          <th>所在地</th>
          <td><%= @animal.customer.prefecture %></td>
        </tr>
      </table>
      
    </div>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th class="customer_edit_th">種類</th>
        <td><%= @animal.tipe_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">性別</th>
        <td><%= @animal.sex_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">誕生日</th>
        <td><%= @animal.birthday %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">所在地</th>
        <td><%= @animal.prefecture %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">ワクチン</th>
        <td><%= @animal.vaccine_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">去勢手術</th>
        <td><%= @animal.castrate_i18n %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">プロフィール</th>
        <td><%= @animal.profile %></td>
      </tr>
      <tr>
        <th class="customer_edit_th">その他</th>
        <td><%= @animal.other %></td>
      </tr>
</table>
</div>
</div>