config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  root to: 'homes#top'
  resources :customers, only: [:show, :edit, :update]
  resources :animals
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :calculation, only: [:index, :show]

  get '/search', to: 'searches#search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :customers, expect: [:new, :destroy, :create]
    resources :animals, expect: [:new, :create, :update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:user_name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture, :city, :house_number,:other, :phone_number, :email )
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_sign_up_params
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture, :])
  #end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
before_action :authenticate_customer!, only: [:edit, :show]

before_action :set_customer, only: [:edit, :update]

def authenticate_customer!
       unless customer_signed_in?
        redirect_to new_customer_session_path
       end
end

  def show
    @customer = Customer.find(params[:id])
    @currentCustomerEntry=Entry.where(customer_id: current_customer.id)
    @customerEntry=Entry.where(customer_id: @customer.id)
    unless @customer.id == current_customer.id
      @currentCustomerEntry.each do |cc|
        @customerEntry.each do |c|
          if cc.room_id == c.room_id then
            @isRoom = true
            @roomId = cc.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    # @customer = Customer.find(params[:id])
  end

  def update
    # @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end
  
  def customer_params
    params.require(:customer).permit(:user_name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture, :city, :house_number,:other, :phone_number, :email )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h2>Wanyan</h2>
  </div>
  <div class ="row">
    <table class="table">
      <thead class ="thead-light">
        <tr>
          <th>ユーザー名</th>
          <th>所在地</th>
        </tr>
      </thead>
      <tbody>
        <%= @customers.each do |customer| %>
          <tr>
            <td><%= link_to customer.user_name, customer_path(customer) %></td>
            <td><% customer.prefecture %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-11 offset-lg-1 ">
　　<h2>顧客画面</h2>
      <span class="title">登録情報<span>
      <span class="customer_edit"><%= link_to "編集する", edit_customer_path,class: "btn btn-sm btn-success" %></span>
      <table border="1" style="border-collapse: collapse" class="customer_show_table">
        <tr>
          <th class="customer_show_th">ユーザー名</th>
          <th class="customer_show_th_content"><%= @customer.user_name %></th>
        </tr>
        <tr>
          <th class="customer_show_th">氏名</th>
          <th class="customer_show_th_content"><%= @customer.last_name + @customer.first_name %></th>
        </tr>
        <tr>
          <th class="customer_show_th">フリガナ</th>
          <th class="customer_show_th_content"><%= @customer.last_name_kana + @customer.first_name_kana %></th>
        </tr>
        <tr>
          <th class="customer_show_th" >郵便番号</th>
          <th class="customer_show_th_content">〒<%= @customer.postcode%></th>
        </tr>
        <tr>
          <th class="customer_show_th">住所</th>
          <th class="customer_show_th_content"><%= @customer.prefecture + @customer.city + @customer.house_number + @customer.other%></th>
        </tr>
        <tr>
          <th class="customer_show_th">電話番号</th>
          <th class="customer_show_th_content"><%= @customer.phone_number%></th>
        </tr>
        <tr>
          <th class="customer_show_th">メールアドレス</th>
          <th class="customer_show_th_content"><%= @customer.email%></th>
        </tr>
    </table>
    <div class="link">
      <h3>募集一覧</h3>
        <div class="row">
          <div class="width">
            <% @customer.animals.each do |animal| %>
              <div class="customer-height">
                <p class="img_wrap">
                  <%= link_to animal_path(animal) do %>
                  <%= attachment_image_tag animal, :image, :fill, 150, 150, format: 'jpeg', class: "img" %>
                  <% end %>
                </p>
                <p>
                  <%= animal.title %>
                </p>
                <p>
                  <%= animal.prefecture %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>
 </div>
</div>