config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  root to: 'homes#top'
  resources :customers, only: [:show, :edit, :update]
  resources :animals
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :calculation, only: [:index, :show]

  get '/search', to: 'searches#search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :customers, expect: [:new, :destroy, :create]
    resources :animals, expect: [:new, :create, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animal.rb
class Animal < ApplicationRecord
  # has_many_attached :images
  attachment :image

  belongs_to :customer
  has_many :searches

  enum tipe: { dog: 0, cat: 1}
  enum sex: { bothsides: 0, male: 1, female: 2}
  enum vaccine: { unknown: 0, already: 1, notyet: 2}
  enum castrate: { humei: 0, sumi: 1, mada: 2}

  scope :search, -> (search_params) do
    return if search_params.blank?

    profile_like(search_params[:profile])
      .prefecture_like(search_params[:gender])
      .tipe_is(search_params[:sex])
      .sex_is(search_params[:gender])
      .vaccine_is(search_params[:gender])
      .castrate_is(search_params[:gender])
  end

  scope :profile_like, -> (profile) { where('profile LIKE ?', "%#{profile}%") if profile.present? }
  scope :prefecture_like, -> (prefecture) { where('prefecture LIKE ?', "%#{prefecture}%") if prefecture.present? }
  scope :tipe_is, -> (tipe) { where(tipe: tipe) if tipe.present? }
  scope :sex_is, -> (sex) { where(sex: sex) if sex.present? }
  scope :vaccine_is, -> (vaccine) { where(vaccine: vaccine) if vaccine.present? }
  scope :castrate_is, -> (castrate) { where(castrate: castrate) if castrate.present? }

# プロフィールによる絞り込み
# scope :get_by_profile, ->profile {
# where("profile like ?", "%#{profile}%")
# }
# 種類による絞り込み
# scope :get_by_tipe, ->(tipe) {
# where(tipe: tipe)
# }

# 性別による絞り込み
# scope :get_by_sex, ->(sex) {
# where(sex: sex)
# }

# ワクチンによる絞り込み
# scope :get_by_vaccine, ->(vaccine) {
# where(vaccine: vaccine)
# }

# 去勢手術による絞り込み
# scope :get_by_castrate, ->(castrate) {
# where(castrate: castrate)
# }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord

  def tribonacci(n)
  return   if n < 1
  a, b, c = 0, 0, 1
  (n - 1).times { a, b, c = b, c, a + b + c }
  a
  end

  def tribonacci n
  if n == 1
    return 1
  elsif n == 2
    return 1
  elsif n == 3
    return 2
  else
    return tribonacci(n - 3) + tribonacci(n - 2) + tribonacci(n - 1)
  end
　end

　def yakusuu

　end

　def fibonacci(input)
  (2...input).inject([1, 1]){ |memo, number|
    memo << (memo[number - 2] + memo[number - 1])
  }
  end

  p fibonacci(10)
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/divisor.rb
class Divisor < ApplicationRecord
  def divisor(num)
  result = []
  i = 1
  while i <= num do
    remainder = num % i
    if remainder == 0
      result << i
    end 
    i += 1
  end
  return result
end

puts "約数を算出したい整数を入力してください"
num = gets.to_i
r = divisor(num)
puts r
puts "約数の数は#{r.length}です"
puts "約数の合計は#{r.sum}です"

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :customer
  belongs_to :room
end

app/models/mini.rb
class Mini < ApplicationRecord
end

app/models/minipro.rb
class Minipro < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :customer
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :animal

  scope :search, -> (search_params) do
    return if search_params.blank?

    profile_like(search_params[:profile])
      .prefecture_like(search_params[:prefecture])
      .tipe_is(search_params[:tipe])
      .sex_is(search_params[:sex])
      .vaccine_is(search_params[:vaccine])
      .castrate_is(search_params[:castrate])
  end

  scope :profile_like, -> (profile) { where('profile LIKE ?', "%#{profile}%") if profile.present? }
  scope :prefecture_like, -> (prefecture) { where('prefecture LIKE ?', "%#{prefecture}%") if prefecture.present? }
  scope :tipe_is, -> (tipe) { where(tipe: tipe) if tipe.present? }
  scope :sex_is, -> (sex) { where(sex: sex) if sex.present? }
  scope :vaccine_is, -> (vaccine) { where(vaccine: vaccine) if vaccine.present? }
  scope :castrate_is, -> (castrate) { where(castrate: castrate) if castrate.present? }


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # def search
  #   if params[:profile].present?
  #     @animals = @animals.get_by_profile params[:profile]
  #   end
  #   if params[:tipe].present?
  #     @animals = @animals.get_by_tipe params[:tipe]
  #   end
  #   if params[:sex].present?
  #     @animals = @animals.get_by_sex params[:sex]
  #   end
  #   if params[:vaccine].present?
  #     @animals = @animals.get_by_vaccine params[:vaccine]
  #   end
  #   if params[:castrate].present?
  #     @animals = @animals.get_by_castrate params[:castrate]
  #   end
  # end
  def search
    @search_params = reservation_search_params
    # @searches = Search.search(@search_params).joins(:animal)
    @searches = Animal.search(@search_params).page(params[:page]).per(8).reverse_order
  end

  private

  def reservation_search_params
    params.fetch(:search, {}).permit(:profile, :tipe, :sex, :prefecture, :vaccine, :castrate)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/java_helper.rb
module JavaHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mini_helper.rb
module MiniHelper
end

app/helpers/minipro_helper.rb
module MiniproHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<div class="search-form">
  <%= form_with(scope: :search, url: search_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label :profile, "キーワード" %>
      <%= f.text_field :profile, placeholder: '半角のみ', value: @search_params[:profile] %>
    </div>
    <div class="field">
      <%= f.label :prefecture, "募集地域" %>
      <%= f.text_field :prefecture, placeholder: '半角のみ', value: @search_params[:prefecture] %>
    </div>
    <div class="field">
      <%= f.label :tipe, "種類" %>
      <%= f.radio_button :tipe, '', {:checked => true} %>指定なし
      <%= f.radio_button :tipe, 0 %>犬
      <%= f.radio_button :tipe, 1 %>猫
    </div>
    <div class="field">
      <%= f.label :sex, "性別" %>
      <%= f.radio_button :sex, '', {:checked => true} %>指定なし
      <%= f.radio_button :sex, 1 %>オス
      <%= f.radio_button :sex, 2 %>メス
      <%= f.radio_button :sex, 0 %>オス・メス
    </div>
    <div class="field">
      <%= f.label :vaccine, "ワクチン" %>
      <%= f.radio_button :vaccine, '', {:checked => true} %>指定なし
      <%= f.radio_button :vaccine, 1 %>済
      <%= f.radio_button :vaccine, 2 %>未
      <%= f.radio_button :vaccine, 0 %>不明
    </div>
    <div class="field">
      <%= f.label :castrate, "去勢手術" %>
      <%= f.radio_button :castrate, '', {:checked => true} %>指定なし
      <%= f.radio_button :castrate, 1 %>済
      <%= f.radio_button :castrate, 2 %>未
      <%= f.radio_button :castrate, 0 %>不明
    </div>
    <%= submit_tag '検索', class: "button" %>
  <% end %>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="width">
　    <% @searches.each do |animal| %>
　      <div class="height">
          <p class="img_wrap">
            <%= link_to animal_path(animal) do %>
              <%= attachment_image_tag animal, :image, :fill, 250, 250, format: 'jpeg', class: "img" %>
            <% end %>
          </p>
          <p>
            <%= animal.title %>
          </p>
          <p>
            <%= animal.prefecture %>
          </p>
        </div>
　    <% end %>
　    <div class="center-block row">
        <%= paginate @searches %>
      </div>
    </div>
  </div>
</div>